name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  notifySlack:
   name: Slack Notification
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: prueba-git
        SLACK_COLOR: '#3275BD'
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Prueba Slack Github Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

